#check-status.yml

---
  - hosts: webservers:loadbalancers
    become: true
    tasks: 
      - name: Check apache status
        command: service httpd status
        changed_when: false

      - name: this will not fail
        command: /bin/false
        ignore_errors: yes

      - name: this will run
        command: /bin/true
        changed_when: false
