#setup-lb.yml

---
  - hosts: loadbalancers
    become: true
    tasks: 
      - name: build config file from template and upload
        template: 
          src: ../config/lb-config.j2
          dest: /etc/httpd/conf.d/lb.conf
          owner: bin
          group: wheel
          mode: 064
        notify: "web server change"

    handlers:      
      - name: restart apache
        service:
          name: httpd
          state: restarted  
        listen: "web server change"
          